### ISSUE TITLE
notty crashes when running "ls"

### ISSUE THREAD

**Issue by waynr** [withoutboats/notty#13]
# System Info

``` bash
+ set -x
+ rustc --version
rustc 1.8.0-dev (dcf8ef272 2016-02-05)
+ cargo --version
cargo 0.9.0 (3e285ce 2016-02-05)
+ git show-ref HEAD
f1cbbec6bdff79f6e4a96e3a9d22815cfaa9c7ec refs/remotes/origin/HEAD
+ cat /etc/debian_version
stretch/sid
+ set +x
```
# Reproduce:

Run `ls` in the `scaffolding` terminal.

**Comment by waynr** [comment]
One further clarification, this only seems to be reproducible using `sh`. I can run `ls` under bash.

**Comment by withoutboats** [comment]
Got a backtrace

```
thread '<main>' panicked at 'not yet implemented', .../notty/src/datatypes/mod.rs:160
stack backtrace:
   1:        0x104abe228 - sys::backtrace::tracing::imp::write::hb21d812ecbcaddablLt
   2:        0x104abf94f - panicking::log_panic::_<closure>::closure.41028
   3:        0x104abf3d1 - panicking::log_panic::h02c8861f7eb14fdaGEx
   4:        0x104ab6ef6 - sys_common::unwind::begin_unwind_inner::h2514f54da0f1ef37nOs
   5:        0x104a4e547 - sys_common::unwind::begin_unwind::begin_unwind::h8668222397122505477
   6:        0x104a513bb - datatypes::move_within::hd3c12d37d8001aeeuRb
   7:        0x104a87421 - terminal::char_grid::cursor::_<impl>::navigate::h89d49f77651b993dw1e
   8:        0x104a4931a - terminal::char_grid::_<impl>::move_cursor::h5d2615a8bfae9f70eWf
   9:        0x104a492a0 - command::movement::_<impl>::apply::he63f9f8ee28ff3b6rHa
  10:        0x104a21040 - commands::_<impl>::apply::h08c2988581cc04a4pba
  11:        0x104a20d6d - main::_<closure>::closure.11288
  12:        0x104ab5003 - extern $u22$rust.call$u22$$u20$fn$LP$$RF$mut$u20$core..ops..FnMut$LP$$RP$$u20$.$GT$$u20$source..Continue$u20$$u2b$$u20$$u27$static$C$$u20$$LP$$RP$$RP$$u20$.$GT$$u20$source..Continue::object_shim.18122::h707c9e4f79c1dacb
  13:        0x104ab4f19 - source::trampoline::__rust_abi
  14:        0x104ab4e94 - source::trampoline::he03f3657ed2ef9f607a
  15:        0x10562c5f6 - g_timeout_dispatch
  16:        0x10562f13a - g_main_context_dispatch
  17:        0x10562f424 - g_main_context_iterate
  18:        0x10562f67a - g_main_loop_run
  19:        0x104da8de9 - gtk_main
  20:        0x104a29fa5 - rt::main::hd2be081a1dc8d20b2ha
  21:        0x104a01066 - main::hbe9963c0b675d347cia
  22:        0x104abf132 - sys_common::unwind::try::try_fn::h3029987471055516238
  23:        0x104abd668 - __rust_try
  24:        0x104abefd9 - rt::lang_start::he1a0c1384f92650fOBx
  25:        0x104a23919 - main
```

The cause is that tabbing past the edge of a line isn't implemented yet. Probably the reason `ls` works for you under bash is that bash is postprocessing `ls` to not output tab characters (once again, spaces win over tabs :laughing:)

**Comment by waynr** [comment]
I added a debug statement so I could see exactly which `Tab` enum pattern was not being matched by 
https://github.com/withoutboats/notty/blob/master/src/datatypes/mod.rs#L146-L159.

I added the debug statement just above this: 
https://github.com/withoutboats/notty/blob/master/scaffolding/src/commands.rs#L33

The debug statement looks like: `println!("{:?}", cmd.repr());`

This led to the following stdin/stdout when I ran the scaffolding app and pressed the `TAB` key once:

```
     Running `target/debug/scaffolding-terminal`
"$"
" "
"KEY PRESS"
"MOVE RIGHT TAB 1"
thread '<main>' panicked at 'not yet implemented', /home/rufusxaviersarsaparilla/projects/notty/src/datatypes/mod.rs:160
stack backtrace:
   1:     0x561401cf8c21 - sys::backtrace::tracing::imp::write::hace912a7e26e5f60Squ
                        at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:40
   2:     0x561401cfe999 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.43684
                        at src/libstd/panicking.rs:180
   3:     0x561401cfe043 - panicking::default_handler::hbe5ea03d8e406ef5xQy
                        at src/libstd/panicking.rs:195
   4:     0x561401cf477d - panicking::on_panic::hd2b96d974192270aTUy
                        at src/libstd/panicking.rs:229
   5:     0x561401cd2d48 - sys_common::unwind::begin_unwind_inner::h81a6fc22c2c84b68qjt
                        at src/libstd/sys/common/unwind/mod.rs:254
   6:     0x561401c63247 - sys_common::unwind::begin_unwind::h17116418807139680588
                        at src/libstd/sys/common/unwind/mod.rs:236
   7:     0x561401c65efc - datatypes::move_within::h94ecade807ebd043uRb
                        at /home/rufusxaviersarsaparilla/projects/notty/scaffolding/<std macros>:3
   8:     0x561401c9d6eb - terminal::char_grid::cursor::Cursor::navigate::hac9e42178486eb3aw1e
                        at /home/rufusxaviersarsaparilla/projects/notty/src/terminal/char_grid/cursor.rs:51
   9:     0x561401c5e076 - terminal::char_grid::CharGrid::move_cursor::hefb3e815ca66d18ceWf
                        at /home/rufusxaviersarsaparilla/projects/notty/src/terminal/char_grid/mod.rs:139
  10:     0x561401c5dff8 - command::movement::Move.Command::apply::h10e4769829d7da45rHa
                        at /home/rufusxaviersarsaparilla/projects/notty/src/command/movement.rs:24
  11:     0x561401c34259 - commands::CommandApplicator::apply::h4353ee5f2de47569pba
                        at src/commands.rs:34
  12:     0x561401c33d4d - main::_$u7b$$u7b$closure$u7d$$u7d$::closure.11441
                        at src/main.rs:79
  13:     0x561401ccbee3 - extern $u22$rust.call$u22$$u20$fn$LP$$RF$mut$u20$core..ops..FnMut$LP$$RP$$u20$.$GT$$u20$source..Continue$u20$$u2b$$u20$$u27$static$C$$u20$$LP$$RP$$RP$$u20$.$GT$$u20$source..Continue::object_shim.18438::hdc6817df2f4cda30
  14:     0x561401ccbdf7 - source::trampoline::__rust_abi
                        at /home/rufusxaviersarsaparilla/.cargo/registry/src/github.com-88ac128001ac3a9a/glib-0.0.7/src/source.rs:35
  15:     0x561401ccbd64 - source::trampoline::hffb499e32f145c2107a
  16:     0x7f08dc6658f2 - <unknown>
  17:     0x7f08dc664e89 - g_main_context_dispatch
  18:     0x7f08dc66522f - <unknown>
  19:     0x7f08dc665551 - g_main_loop_run
  20:     0x7f08ddd6be34 - gtk_main
  21:     0x561401c3d6f5 - rt::main::h9e6163b74d1ea44e6ha
                        at /home/rufusxaviersarsaparilla/.cargo/registry/src/github.com-88ac128001ac3a9a/gtk-0.0.6/src/rt.rs:99
  22:     0x561401c12538 - main::hd26aa6938fd2d59eJia
                        at src/main.rs:121
  23:     0x561401cfd842 - fn()::fn_pointer_shim.43658::hdf162b9a7d7c9643
  24:     0x561401cfd64d - panic::recover::_$u7b$$u7b$closure$u7d$$u7d$::closure.43653
                        at src/libstd/panic.rs:260
  25:     0x561401cfd629 - sys_common::unwind::try::try_fn::h8076503571907045097
                        at src/libstd/sys/common/unwind/mod.rs:127
  26:     0x561401cf3ac7 - __rust_try
  27:     0x561401cf37e2 - sys_common::unwind::inner_try::_$u7b$$u7b$closure$u7d$$u7d$::closure.42658
                        at src/libstd/sys/common/unwind/mod.rs:149
  28:     0x561401cf36e3 - thread::local::LocalKey<T>::with::h11300722055371691439
                        at src/libstd/thread/local.rs:211
  29:     0x561401ce40fc - sys_common::unwind::inner_try::h7dd260a96ffa8148sgt
                        at src/libstd/sys/common/unwind/mod.rs:134
  30:     0x561401cfd5d8 - sys_common::unwind::try::h17419640952346635745
                        at src/libstd/sys/common/unwind/mod.rs:123
  31:     0x561401cfd42c - panic::recover::h12526663432070526086
                        at src/libstd/panic.rs:260
  32:     0x561401cfd31c - rt::lang_start::h2790f89d9b014e5cDIy
                        at src/libstd/rt.rs:63
  33:     0x561401c36b19 - main
  34:     0x7f08dc29786f - __libc_start_main
  35:     0x561401c115f8 - _start
  36:                0x0 - <unknown>
Process didn't exit successfully: `target/debug/scaffolding-terminal` (exit code: 101)
```

What confuses me is this `"MOVE RIGHT TAB 1"` which I think comes from here:
https://github.com/withoutboats/notty/blob/master/src/command/movement.rs#L38

which makes me think that this pattern should match:
https://github.com/withoutboats/notty/blob/master/src/datatypes/mod.rs#L156

Unless of course the third member of the `Tab` tuple happens to be `true`...so I made the case at line 156 in the last link more general in a PR, #17

I'm still not sure what it means for that third `Tab` tuple value to be `true`, @withoutboats could you explain that? I am fairly certain this is where the value is coming from:
https://github.com/withoutboats/notty/blob/master/src/output/mod.rs#L57

But even there it's not clear to me what its significance is. Any explanation would be helpful, thanks!
